### ISSUE TITLE
unmute

### ISSUE THREAD

**Issue by PhilMDev** [asterisk/node-ari-client#11] opened 2014-12-29 20:55 UTC
I was attempting to use the mute and unmute channel options.  The mute option worked just fine but the unmute didn't.  If I used the direct Swagger UI delete mute call it was able to unmute the channel just fine.

Have you had any reports of this?  I found another way around the issue.  I was setting the role of a bridge to mixing when I should've been setting it to holding.  But, I'm sure I'll need mute and unmute in the future.

Thank you!
Phil Mickelson

**Comment by samuelg** [comment] 2015-01-02 19:50
What version of Asterisk are you running on? I seem to remember an issue
with mute/unmute via ARI but cannot find the related issue.

Can you provide code example of what you are trying to accomplish? Swagger
UI will often work where using a library will not because the HTML forms
often provide defaults for various operations. It's possible you are simply
missing an option when calling unmute.


On Mon, Dec 29, 2014 at 2:55 PM, PhilMDev <notifications@github.com> wrote:

> I was attempting to use the mute and unmute channel options. The mute
> option worked just fine but the unmute didn't. If I used the direct Swagger
> UI delete mute call it was able to unmute the channel just fine.
>
> Have you had any reports of this? I found another way around the issue. I
> was setting the role of a bridge to mixing when I should've been setting it
> to holding. But, I'm sure I'll need mute and unmute in the future.
>
> Thank you!
> Phil Mickelson
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/asterisk/node-ari-client/issues/11>.
>



-- 
Samuel Fortier Galarneau

**Comment by PhilMDev** [comment] 2015-01-02 19:59
Not sure if you want me to answer via email or not but I'll start here.

I was using the latest version of Asterisk - 13.1.0.

The code was:

    ariPtr.channels.mute({channelId:move_channel,
direction:'in'},function(err){
        if (err){
            log.error('set channel to mute - move to ring bridge: '+err);
        } else {




make sure the operator's mute in is no longer set.
ariPtr.channels.unmute({channelId: 'chan'+reply.send_to,direction:
'in'},function(err){
    if (err){
//if there is an error display here.
        log.error('channel unmute - answer call: '+err);
    } else {

I never received an error.  However, when I watched the debug screen the
call never showed up as being received.  It was almost like Asterisk was
never called.

BTW, I also tried 'both' when doing unmute just in case.  Made no
difference.  Again, the mute worked, the unmute didn't.

Thanks!
Phil Mickelson

**Comment by samuelg** [comment] 2015-01-05 23:03
I tried to reproduce this with Asterisk 13.1 and was not able to. Both mute and unmute worked fine for me in a mixing bridge.

Since this works with Swagger UI for you I suspect move_channel and 'chan' + reply.send_to may not in fact match.

If that is not the case I'm afraid I will need more of your code to go on to figure out why the unmute operation is not working properly.

**Comment by PhilMDev** [comment] 2015-01-06 01:00
Let me see if I can setup a test.  I've got a bunch of things to do right
now but I'll do my best.  This is also something that I suspect Digium
would like to see since Asterisk shut down while this was happening.  They
tested the system using holding bridges instead of mixing and it worked
just fine.  So, I suspect they can move forward and there's not as much
concern about this issue.

FYI, I've been writing software for almost 40 years now.  I've done more
than my fair share of support and I understand how difficult it is to
convince people to make sure they check all the various and sundry
options.  I always try to have something that can be duplicated.
Unfortunately, in this case, there are just too many moving parts.
However, I will do my best to setup a repeatable case.  And, I really
appreciate you taking the time to look at this.

Phil Mickelson

**Comment by samuelg** [comment] 2015-01-06 15:38
I didn't know the issue causes Asterisk to shut down. Would you mind opening an issue on https://issues.asterisk.org? This doesn't sound like a client issue at this point.

thanks

**Comment by samuelg** [comment] 2015-01-06 15:38
Closing for now as it appears this should be fixed upstream.

**Closed by samuelg** 2015-01-06 15:38 UTC

**Comment by PhilMDev** [comment] 2015-01-06 15:40
I will.  Thanks!
